apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
  labels:
    app.kubernetes.io/name: guestbook-project
spec:
  description: "Project for the agent2agent guestbook application"
  
  # Source repositories that applications in this project can deploy from
  sourceRepos:
    - https://github.com/rhprasad0/aws-devops-lab
  
  # Destination clusters and namespaces
  destinations:
    - namespace: guestbook
      server: https://kubernetes.default.svc
  
  # Namespace-scoped resources that can be deployed
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: networking.k8s.io
      kind: Ingress
    # Argo Rollouts CRDs for canary/blue-green deployments (Week 9)
    - group: argoproj.io
      kind: Rollout
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: argoproj.io
      kind: AnalysisRun
  
  # Cluster-scoped resources that are explicitly allowed
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  
  # Cluster-scoped resources that are explicitly denied
  clusterResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
